### ISSUE TITLE
Add SHACL inference to models before hosting

### ISSUE THREAD

**Issue by gtfierro** [open223/models.open223.info#10]
I need to adopt the compilation process from the query.open223.info page to add all inferred triples to these models before they are hosted, to ensure the queries run as expected

**Comment by michaelpoplawskipnnl** [comment]
@gtfierro what does the automated process do if the validation produces info, warnings, and/or violations?

**Comment by gtfierro** [comment]
After #21 is merged, it will break the build and let you know what the error is.
