### ISSUE TITLE
Supporting development of user experience with inference and validation

### ISSUE THREAD

**Issue by michaelpoplawskipnnl** [open223/models.open223.info#16]
Should these models support the development of user experiences with inference and validation?

We found that setting up inference and validation with both pyshacl and topquadrant api to be not as straightforward as we initially thought/hoped. Documentation for both could be improved, and mistaken assumptions can lead to issues. Thus, I think we should.
Two ideas:

1.  Should we post model versions both a) pre- inferencing and validation, and b)  post- inferencing and validation?
2. Should we start "versioning" the ontology (including inferencing and validation code)? If we did such, we could post on the model pages that:

- "This model was created using ontology version ##.#."
- "Validation resulted in # warnings and # errors."

**Comment by michaelpoplawskipnnl** [comment]
From the 1/9/23 meeting, it sounds like there is general consensus to provide both versions of a model - one prior to inferencing and validation, and one post. @gtfierro proposed an update to the workflow that would automatically run a local (to this repo) inferencing and validation, and thus support this capability.

**Comment by gtfierro** [comment]
I've already created an issue for this: https://github.com/open223/models.open223.info/issues/10

**Comment by michaelpoplawskipnnl** [comment]
@gtfierro your issue and resolution did not address point #2 above. Thoughts?
@steveraysteveray @pdelgosha22 and I discussed this recently too. Thoughts?
I recall that @MatthewSteen has thoughts about this too?

**Comment by gtfierro** [comment]
We are still pre-release . I think it is overkill to debate hypothetical versioning scenarios until we know what the maintenance of the standard will look like

**Comment by MatthewSteen** [comment]
I enabled `Discussions` for the repo in case that's useful for discussing potential `Issues`.
