### ISSUE TITLE
"Publication document is not yet publicly published"

### ISSUE THREAD

**Issue by VladimirAlexiev** [open223/models.open223.info#34]
https://github.com/open223/models.open223.info/blob/main/intro.md has this note:
> Publication document is not yet publicly published

IMHO this note is not understandable, and it doesn't make it clear which document is not published.

In contrast, https://docs.open223.info/intro.html has an understandable note:
> The proposed standard is not yet available for public review.

**Comment by gtfierro** [comment]
Thanks for pointing this out! I've clarified the language
