### ISSUE TITLE
explain "compiled" models

### ISSUE THREAD

**Issue by VladimirAlexiev** [open223/models.open223.info#35]
https://models.open223.info/examples/bdg1-1.html (and most other models) have two variants:
> [Turtle file (compiled)](https://models.open223.info/compiled/bdg1-1.ttl) ([original](https://models.open223.info/bdg1-1.ttl))

By eyeballing, "Compiled" is much worse since it uses generated prefixes (eg `ns2:`) and doesn't use instance data prefixes.
So please explain in the intro what are Compiled models for and whether they include more info than Original models.

Maybe the only benefit is that ValidationReports print instance URLs in full, so it's a bit easier to look them up in the Compiled model?
> `ns2:commandedByProperty is not defined for instance <http://data.ashrae.org/standard223/1.0/data/pd-sr-mp-pritoni#VAVBox2ReheatValveActuator>.`

**Comment by VladimirAlexiev** [comment]
https://github.com/open223/models.open223.info/issues/54 by @steveraysteveray 
suggests that "compiling" makes iterative inference, as much as 5 iterations.

I've seen presentations by @gtfierro that show how 233 has a lot more nodes (details) than Bricks and Haystack, yet you can derive one from the other.

Is compilation related to this?

**Comment by VladimirAlexiev** [comment]
#10 and https://github.com/open223/models.open223.info/blob/main/tools/compile.py suggest that SHACL rules are applied

**Comment by steveraysteveray** [comment]
Yes, they are.
