### ISSUE TITLE
How are you deploying the additional IBAL Queries

### ISSUE THREAD

**Issue by lazlop** [open223/models.open223.info#8]
Hi @BradEstacio How are you deploying the gh page from your branch? It appears that it's just configured to use the main branch.

**Comment by BradEstacio** [comment]
Oh I see what you're talking about. To be honest, I don't know. I'm guessing every time I push to the repository it's updated even if it's not on the main branch, though from what you're saying that shouldn't happen.

**Comment by gtfierro** [comment]
Please only submit the PRs to the `main` branch. The `gh-pages` branch will get updated automatically during the build process. Let me know if the README in this repo answers your questions or if there is something still unclear!
